include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    # Error prevention
    always_declare_return_types: true
    avoid_print: true
    avoid_dynamic_calls: true
    avoid_empty_else: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    use_key_in_widget_constructors: true
    
    # Style
    prefer_single_quotes: true
    require_trailing_commas: true
    sort_child_properties_last: true
    
    # Best practices
    avoid_unnecessary_containers: true
    prefer_final_fields: true
    prefer_final_locals: true
    use_build_context_synchronously: true
